name: PepCCD
channels:
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - cd-hit=4.8.1=h2e03b76_5
  - gawk=5.3.1=h5eee18b_0
  - gettext=0.21.0=hedfda30_2
  - icu=73.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libunistring=0.9.10=h27cfd23_0
  - libxml2=2.13.5=hfdd30dd_0
  - mmseqs2=13.45111=h95f258a_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.17=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - seqtk=1.2=0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wget=1.25.0=h251f7ec_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - biopython==1.83
      - blobfile==3.0.0
      - cachetools==5.5.2
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - chex==0.1.7
      - click==8.1.7
      - colorama==0.4.6
      - configparser==7.1.0
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.11
      - dataclasses==0.6
      - datasets==3.1.0
      - decorator==5.1.0
      - dill==0.3.8
      - dllogger==1.1.0
      - dm-haiku==0.0.14
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - dscript==0.2.8
      - e3nn==0.3.3
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - fair-esm==2.0.0
      - fairscale==0.4.13
      - fairseq==0.10.2
      - filelock==3.16.1
      - fire==0.7.0
      - fonttools==4.55.2
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gdown==5.2.0
      - gemmi==0.7.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google==3.0.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - huggingface-hub==0.29.1
      - hydra-core==1.3.2
      - idna==3.10
      - immutabledict==4.2.1
      - importlib-resources==6.4.5
      - info-nce-pytorch==0.1.4
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.4
      - jmp==0.0.4
      - joblib==1.4.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - lxml==5.3.0
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.1
      - nltk==3.9.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - optax==0.1.8
      - packaging==24.1
      - pandas==2.0.3
      - parasail==1.3.4
      - pathtools==0.1.2
      - patsy==1.0.1
      - peptidebuilder==1.1.0
      - pillow==10.4.0
      - pip==24.0
      - portalocker==3.0.0
      - promise==2.3
      - propcache==0.2.0
      - protobuf==3.20.1
      - psutil==6.1.1
      - py3dmol==2.4.2
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodomex==3.21.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeprecate==0.3.2
      - pynvml==11.0.0
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.6.5
      - pytorch-metric-learning==2.1.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scikit-learn==1.3.2
      - scikit-posthocs==0.8.1
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.27.0
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.6
      - statsmodels==0.14.1
      - stdiomask==0.0.6
      - subprocess32==3.5.4
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.1
      - toolz==1.0.0
      - torch==2.4.1
      - torch-geometric==2.3.0
      - torchaudio==2.4.1
      - torchdata==0.8.0
      - torchmetrics==1.5.2
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.45.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - viennarna==2.7.0
      - wandb==0.21.4
      - werkzeug==3.0.6
      - xxhash==3.5.0
      - yarl==1.15.2
      - zipp==3.20.2

